### ISSUE TITLE
Sugerencia de implementacion depatrón Abstract Factory Mehtod

### ISSUE THREAD

**Issue by gnpazmin** [GisTypical/ZoologicoPOO#8]
Hola revise el programa y te propongo posibles implementaciones de patrones de diseño que mejoraran el funcionamiento y organización del código ya existente. 

Identifique que es posible utilizar Abstract Factory Mehtod.
El motivo por el cual se sugiere utilizar este patrón es porque dentro del programa existen muchos tipos animales que pertenecen al zoológico tales como anfibios, aves, peces, mamíferos y reptiles. 
Para poder organizar de mejor manera el código se crea interfaces para cada tipo de animal con sus características específicas correspondientes. También se implementa una interfaz general llamada “Animales” que nos sirve como comunicador entre las interfaces de cada especie con la clase Zoológico. 
Es muy importante esta implementación ya que aunque aumenta la cantidad de código y de clases y puede resultar un poco largo y tedioso ayuda mucho a la organización, funcionalidad y reutilización del código. 

Te adjunto tambien un diagrama de clases uml con la explicacion de lo antes mencionado. 

[Factory Abstract Method_UML.pdf](https://github.com/GisTypical/ZoologicoPOO/files/5048791/Factory.Abstract.Method_UML.pdf)

**Comment by GisTypical** [comment]
¡Hola!, estoy agradecido por tomarte el tiempo para darme tu sugerencia, como también para el diagrama UML, tomaré muy en cuenta ese patrón de diseño para una futura actualización, ya que quisiera seguir aprendiendo mucho más en terminos de OOP.
